name: Build and Push Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: cr.yandex
  IMAGE_NAME: docker-demo-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_SA_PRIVATE_KEY }}" | docker login \
            --username oauth \
            --password-stdin cr.yandex

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:${{ github.sha }} .
          docker tag $REGISTRY/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:${{ github.sha }} \
                     $REGISTRY/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $REGISTRY/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:latest
